<?php

namespace Database\Seeders;

use App\Models\Category;
use App\Models\Product;
use App\Models\Store;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    public function run(): void
    {
        $storesByName = Store::query()->get()->keyBy('store_name');
        $categoriesByName = Category::query()->get()->keyBy('name');

        $catalog = [
            "Pedro's Palengke" => [
                [
                    'name' => 'Fresh Pork Liempo',
                    'description' => 'Locally sourced pork belly, freshly cut and ideal for grilling or adobo.',
                    'price' => 365.00,
                    'stock' => 18,
                    'sku' => 'PP-BUT-001',
                    'condition' => 'Fresh',
                    'brand' => 'Pedro Fresh Cuts',
                    'weight' => '1kg',
                    'dimensions' => '30 x 18 x 6 cm',
                    'status' => 'active',
                ],
                [
                    'name' => 'Dressed Chicken Whole',
                    'description' => 'Cleaned whole chicken, ready for roasting, frying, or soup dishes.',
                    'price' => 255.00,
                    'stock' => 12,
                    'sku' => 'PP-BUT-002',
                    'condition' => 'Fresh',
                    'brand' => 'Pedro Fresh Cuts',
                    'weight' => '1.2kg',
                    'dimensions' => '28 x 16 x 10 cm',
                    'status' => 'active',
                ],
                [
                    'name' => 'Brown Eggs Tray',
                    'description' => 'Thirty medium brown eggs packed in a tray for daily household use.',
                    'price' => 245.00,
                    'stock' => 20,
                    'sku' => 'PP-BUT-003',
                    'condition' => 'Fresh',
                    'brand' => 'Pedro Farm Goods',
                    'weight' => '30 pcs',
                    'dimensions' => '30 x 30 x 6 cm',
                    'status' => 'active',
                ],
                [
                    'name' => 'Tilapia Cleaned',
                    'description' => 'Fresh tilapia cleaned and scaled, perfect for frying or sinigang.',
                    'price' => 210.00,
                    'stock' => 0,
                    'sku' => 'PP-BUT-004',
                    'condition' => 'Fresh',
                    'brand' => 'Pedro Sea Harvest',
                    'weight' => '1kg',
                    'dimensions' => '32 x 14 x 5 cm',
                    'status' => 'out_of_stock',
                ],
            ],
            "Lorna's Sari-Sari" => [
                [
                    'name' => 'Instant Noodles Family Pack',
                    'description' => 'Value pack of classic instant noodles for quick merienda or midnight snacks.',
                    'price' => 89.00,
                    'stock' => 35,
                    'sku' => 'LSS-CON-001',
                    'condition' => 'New',
                    'brand' => 'Lucky Me',
                    'weight' => '6 x 55g',
                    'dimensions' => '18 x 12 x 8 cm',
                    'status' => 'active',
                ],
                [
                    'name' => '3-in-1 Coffee Mix',
                    'description' => 'Convenient sachet coffee mix with creamy taste for busy mornings.',
                    'price' => 132.00,
                    'stock' => 28,
                    'sku' => 'LSS-CON-002',
                    'condition' => 'New',
                    'brand' => 'Great Taste',
                    'weight' => '20 sachets',
                    'dimensions' => '16 x 10 x 5 cm',
                    'status' => 'active',
                ],
                [
                    'name' => 'Assorted Biscuit Pack',
                    'description' => 'Mixed snack biscuits packed for sari-sari counter display and impulse buys.',
                    'price' => 75.00,
                    'stock' => 22,
                    'sku' => 'LSS-CON-003',
                    'condition' => 'New',
                    'brand' => 'Fiesta Bites',
                    'weight' => '10 packs',
                    'dimensions' => '22 x 14 x 6 cm',
                    'status' => 'draft',
                ],
                [
                    'name' => 'Canned Sardines Bundle',
                    'description' => 'Bundle of tomato sauce sardines, a pantry staple for quick meals.',
                    'price' => 118.00,
                    'stock' => 16,
                    'sku' => 'LSS-CON-004',
                    'condition' => 'New',
                    'brand' => '555',
                    'weight' => '4 x 155g',
                    'dimensions' => '18 x 7 x 9 cm',
                    'status' => 'active',
                ],
            ],
            "Rick's Hardware" => [
                [
                    'name' => 'Steel Nails Assorted',
                    'description' => 'Durable assorted steel nails for woodwork, repairs, and general construction.',
                    'price' => 95.00,
                    'stock' => 40,
                    'sku' => 'RHW-HAR-001',
                    'condition' => 'New',
                    'brand' => 'BuildPro',
                    'weight' => '1kg',
                    'dimensions' => '15 x 10 x 5 cm',
                    'status' => 'active',
                ],
                [
                    'name' => 'Measuring Tape 5m',
                    'description' => 'Compact 5-meter measuring tape with lock feature for home and site use.',
                    'price' => 165.00,
                    'stock' => 14,
                    'sku' => 'RHW-HAR-002',
                    'condition' => 'New',
                    'brand' => 'MetricMax',
                    'weight' => '350g',
                    'dimensions' => '8 x 8 x 4 cm',
                    'status' => 'active',
                ],
                [
                    'name' => 'Latex Wall Paint White',
                    'description' => 'Interior latex paint with smooth finish and reliable wall coverage.',
                    'price' => 685.00,
                    'stock' => 10,
                    'sku' => 'RHW-HAR-003',
                    'condition' => 'New',
                    'brand' => 'ColorGuard',
                    'weight' => '4L',
                    'dimensions' => '18 x 18 x 20 cm',
                    'status' => 'active',
                ],
                [
                    'name' => 'PVC Electrical Tape',
                    'description' => 'Insulating tape for cable management, minor repairs, and electrical projects.',
                    'price' => 32.00,
                    'stock' => 0,
                    'sku' => 'RHW-HAR-004',
                    'condition' => 'New',
                    'brand' => 'VoltSafe',
                    'weight' => '1 roll',
                    'dimensions' => '7 x 7 x 2 cm',
                    'status' => 'out_of_stock',
                ],
            ],
            "Gemma's Bakeshop" => [
                [
                    'name' => 'Classic Pandesal Pack',
                    'description' => 'Freshly baked soft pandesal, perfect for breakfast and merienda.',
                    'price' => 45.00,
                    'stock' => 30,
                    'sku' => 'GBK-BAK-001',
                    'condition' => 'Fresh',
                    'brand' => "Gemma's Bakeshop",
                    'weight' => '10 pcs',
                    'dimensions' => '20 x 12 x 8 cm',
                    'status' => 'active',
                ],
                [
                    'name' => 'Cheese Ensaymada Box',
                    'description' => 'Soft ensaymada topped with butter, sugar, and grated cheese.',
                    'price' => 180.00,
                    'stock' => 14,
                    'sku' => 'GBK-BAK-002',
                    'condition' => 'Fresh',
                    'brand' => "Gemma's Bakeshop",
                    'weight' => '6 pcs',
                    'dimensions' => '24 x 16 x 8 cm',
                    'status' => 'active',
                ],
                [
                    'name' => 'Loaf Bread',
                    'description' => 'Daily baked loaf bread for sandwiches, toast, and family breakfasts.',
                    'price' => 72.00,
                    'stock' => 18,
                    'sku' => 'GBK-BAK-003',
                    'condition' => 'Fresh',
                    'brand' => "Gemma's Bakeshop",
                    'weight' => '600g',
                    'dimensions' => '28 x 12 x 10 cm',
                    'status' => 'active',
                ],
                [
                    'name' => 'Chocolate Cake Slice',
                    'description' => 'Rich chocolate cake slice for dessert counters and cafe-style servings.',
                    'price' => 95.00,
                    'stock' => 8,
                    'sku' => 'GBK-BAK-004',
                    'condition' => 'Fresh',
                    'brand' => "Gemma's Bakeshop",
                    'weight' => '1 slice',
                    'dimensions' => '12 x 10 x 7 cm',
                    'status' => 'draft',
                ],
            ],
            'TechZone PH' => [
                [
                    'name' => 'Fast Charging USB-C Cable',
                    'description' => 'Durable USB-C cable with fast charging support for modern smartphones.',
                    'price' => 199.00,
                    'stock' => 24,
                    'sku' => 'TZP-ELE-001',
                    'condition' => 'New',
                    'brand' => 'TechZone',
                    'weight' => '1m',
                    'dimensions' => '12 x 9 x 3 cm',
                    'status' => 'active',
                ],
                [
                    'name' => '20W Wall Charger',
                    'description' => 'Compact wall charger designed for efficient charging at home or travel.',
                    'price' => 349.00,
                    'stock' => 15,
                    'sku' => 'TZP-ELE-002',
                    'condition' => 'New',
                    'brand' => 'VoltEdge',
                    'weight' => '120g',
                    'dimensions' => '9 x 5 x 4 cm',
                    'status' => 'active',
                ],
                [
                    'name' => 'Wireless Earbuds',
                    'description' => 'Portable wireless earbuds with charging case for music and calls.',
                    'price' => 899.00,
                    'stock' => 9,
                    'sku' => 'TZP-ELE-003',
                    'condition' => 'New',
                    'brand' => 'SonicBeat',
                    'weight' => '80g',
                    'dimensions' => '10 x 8 x 4 cm',
                    'status' => 'active',
                ],
                [
                    'name' => '10000mAh Power Bank',
                    'description' => 'Slim emergency power bank for on-the-go charging during long days out.',
                    'price' => 1150.00,
                    'stock' => 0,
                    'sku' => 'TZP-ELE-004',
                    'condition' => 'New',
                    'brand' => 'ChargeUp',
                    'weight' => '220g',
                    'dimensions' => '14 x 7 x 2 cm',
                    'status' => 'out_of_stock',
                ],
            ],
            "Arlene's Beauty Hub" => [
                [
                    'name' => 'Hydrating Facial Wash',
                    'description' => 'Gentle facial cleanser for daily use with a refreshing, non-drying finish.',
                    'price' => 245.00,
                    'stock' => 20,
                    'sku' => 'ABH-BEA-001',
                    'condition' => 'New',
                    'brand' => 'GlowLab',
                    'weight' => '100ml',
                    'dimensions' => '15 x 6 x 4 cm',
                    'status' => 'active',
                ],
                [
                    'name' => 'Brightening Body Lotion',
                    'description' => 'Moisturizing body lotion formulated for smooth and nourished skin.',
                    'price' => 189.00,
                    'stock' => 17,
                    'sku' => 'ABH-BEA-002',
                    'condition' => 'New',
                    'brand' => 'SilkBloom',
                    'weight' => '250ml',
                    'dimensions' => '18 x 7 x 5 cm',
                    'status' => 'active',
                ],
                [
                    'name' => 'Keratin Repair Shampoo',
                    'description' => 'Salon-inspired shampoo that helps smooth and strengthen dry hair.',
                    'price' => 320.00,
                    'stock' => 13,
                    'sku' => 'ABH-BEA-003',
                    'condition' => 'New',
                    'brand' => 'SalonCare',
                    'weight' => '400ml',
                    'dimensions' => '20 x 8 x 5 cm',
                    'status' => 'active',
                ],
                [
                    'name' => 'Tinted Lip Balm',
                    'description' => 'Pocket-friendly lip balm with soft tint and moisturizing formula.',
                    'price' => 129.00,
                    'stock' => 11,
                    'sku' => 'ABH-BEA-004',
                    'condition' => 'New',
                    'brand' => 'Petal Kiss',
                    'weight' => '4g',
                    'dimensions' => '9 x 2 x 2 cm',
                    'status' => 'draft',
                ],
            ],
            "Kuya Ed's Carinderia" => [
                [
                    'name' => 'Chicken Adobo Meal Pack',
                    'description' => 'Ready-to-serve chicken adobo meal with rice, good for one person.',
                    'price' => 95.00,
                    'stock' => 15,
                    'sku' => 'KEC-RES-001',
                    'condition' => 'Freshly Cooked',
                    'brand' => "Kuya Ed's Kitchen",
                    'weight' => '1 serving',
                    'dimensions' => '20 x 14 x 6 cm',
                    'status' => 'active',
                ],
                [
                    'name' => 'Pork Menudo Tray',
                    'description' => 'Hearty pork menudo packed in a tray for lunch orders and takeout.',
                    'price' => 135.00,
                    'stock' => 10,
                    'sku' => 'KEC-RES-002',
                    'condition' => 'Freshly Cooked',
                    'brand' => "Kuya Ed's Kitchen",
                    'weight' => '2 servings',
                    'dimensions' => '22 x 16 x 6 cm',
                    'status' => 'active',
                ],
                [
                    'name' => 'Lumpiang Shanghai Pack',
                    'description' => 'Crispy lumpiang shanghai rolls bundled for parties and family meals.',
                    'price' => 160.00,
                    'stock' => 12,
                    'sku' => 'KEC-RES-003',
                    'condition' => 'Freshly Cooked',
                    'brand' => "Kuya Ed's Kitchen",
                    'weight' => '12 pcs',
                    'dimensions' => '24 x 14 x 5 cm',
                    'status' => 'active',
                ],
                [
                    'name' => 'Pancit Canton Bilao Mini',
                    'description' => 'Small bilao of pancit canton for office snacks and simple gatherings.',
                    'price' => 420.00,
                    'stock' => 0,
                    'sku' => 'KEC-RES-004',
                    'condition' => 'Made to Order',
                    'brand' => "Kuya Ed's Kitchen",
                    'weight' => 'Mini bilao',
                    'dimensions' => '30 x 30 x 8 cm',
                    'status' => 'out_of_stock',
                ],
            ],
            'FreshPick Fruits' => [
                [
                    'name' => 'Sweet Mangoes',
                    'description' => 'Ripe sweet mangoes selected daily from trusted farm suppliers.',
                    'price' => 180.00,
                    'stock' => 22,
                    'sku' => 'FPF-FRV-001',
                    'condition' => 'Fresh',
                    'brand' => 'FreshPick',
                    'weight' => '1kg',
                    'dimensions' => '24 x 16 x 10 cm',
                    'status' => 'active',
                ],
                [
                    'name' => 'Lakatan Bananas',
                    'description' => 'Naturally sweet lakatan bananas ideal for snacks and smoothies.',
                    'price' => 95.00,
                    'stock' => 26,
                    'sku' => 'FPF-FRV-002',
                    'condition' => 'Fresh',
                    'brand' => 'FreshPick',
                    'weight' => '1kg',
                    'dimensions' => '24 x 14 x 10 cm',
                    'status' => 'active',
                ],
                [
                    'name' => 'Red Tomatoes',
                    'description' => 'Fresh red tomatoes for salads, stews, and everyday cooking.',
                    'price' => 68.00,
                    'stock' => 30,
                    'sku' => 'FPF-FRV-003',
                    'condition' => 'Fresh',
                    'brand' => 'FreshPick',
                    'weight' => '1kg',
                    'dimensions' => '22 x 15 x 8 cm',
                    'status' => 'active',
                ],
                [
                    'name' => 'White Onions',
                    'description' => 'Kitchen staple white onions with firm bulbs and strong flavor.',
                    'price' => 120.00,
                    'stock' => 0,
                    'sku' => 'FPF-FRV-004',
                    'condition' => 'Fresh',
                    'brand' => 'FreshPick',
                    'weight' => '1kg',
                    'dimensions' => '20 x 14 x 8 cm',
                    'status' => 'out_of_stock',
                ],
            ],
        ];

        foreach ($catalog as $storeName => $products) {
            $store = $storesByName->get($storeName);

            if (!$store) {
                $this->command?->warn("Skipping products for missing store: {$storeName}");
                continue;
            }

            $category = $categoriesByName->firstWhere('id', $store->category_id);

            if (!$category) {
                $this->command?->warn("Skipping products for store without category: {$storeName}");
                continue;
            }

            foreach ($products as $productData) {
                $stock = $productData['status'] === 'out_of_stock' ? 0 : $productData['stock'];

                Product::updateOrCreate(
                    [
                        'store_id' => $store->id,
                        'sku' => $productData['sku'],
                    ],
                    [
                        'store_id' => $store->id,
                        'category_id' => $category->id,
                        'name' => $productData['name'],
                        'description' => $productData['description'],
                        'price' => $productData['price'],
                        'stock' => $stock,
                        'sku' => $productData['sku'],
                        'condition' => $productData['condition'],
                        'brand' => $productData['brand'],
                        'weight' => $productData['weight'],
                        'dimensions' => $productData['dimensions'],
                        'status' => $productData['status'],
                    ]
                );
            }
        }
    }
}
